export enum BmiStatus {
  STARVATION = "STARVATION",
  EMACIATED = "EMACIATED",
  UNDERWEIGHT = "UNDERWEIGHT",
  NORMAL = "NORMAL",
  OVERWEIGHT = "OVERWEIGHT",
  OBESITY1 = "OBESITY1",
  OBESITY2 = "OBESITY2",
  OBESITY3 = "OBESITY3"
}

export const BmiStatus2LabelMapping = {
  [BmiStatus.STARVATION]: "PAGES.BODYDATA.BMI_STATUSES." + BmiStatus.STARVATION,
  [BmiStatus.EMACIATED]: "PAGES.BODYDATA.BMI_STATUSES." + BmiStatus.EMACIATED,
  [BmiStatus.UNDERWEIGHT]: "PAGES.BODYDATA.BMI_STATUSES." + BmiStatus.UNDERWEIGHT,
  [BmiStatus.NORMAL]: "PAGES.BODYDATA.BMI_STATUSES." + BmiStatus.NORMAL,
  [BmiStatus.OVERWEIGHT]: "PAGES.BODYDATA.BMI_STATUSES." + BmiStatus.OVERWEIGHT,
  [BmiStatus.OBESITY1]: "PAGES.BODYDATA.BMI_STATUSES." + BmiStatus.OBESITY1,
  [BmiStatus.OBESITY2]: "PAGES.BODYDATA.BMI_STATUSES." + BmiStatus.OBESITY2,
  [BmiStatus.OBESITY3]: "PAGES.BODYDATA.BMI_STATUSES." + BmiStatus.OBESITY3
}
